Metrics/MethodLength:
  Exclude:
    - 'app/controllers/main_controller.rb'

Metrics/AbcSize:
  Exclude:
    - 'app/controllers/main_controller.rb'

Metrics/BlockLength:
  Exclude:
    - 'config/environments/development.rb'